name: "Build Python for Android wth MacOS emulator"

on: [push, pull_request]

jobs:
  build-android:
    name: ${{ matrix.ndk-arch }} on ${{ matrix.arch }} Android
    runs-on: macos-11
    strategy:
      matrix:
        ndk-arch: [x86_64]
        arch: [x86_64]
        api-level: [21]
        target: [default]
        include:
          - ndk-arch: arm64-v8a
            arch: x86_64
            api-level: 30
            target: google_apis
          - ndk-arch: x86
            arch: x86
            api-level: 21
            target: default
          - ndk-arch: armeabi-v7a
            arch: x86_64
            api-level: 30
            target: google_apis

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: create directories
      run: |
        mkdir -p build-python/python-cmake-buildsystem

    - uses: actions/cache@v2
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
          ~/.android/debug.keystore
        key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}

    - name: run emulator to generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: ${{ matrix.arch }}
        profile: Galaxy Nexus
        cores: 2
        sdcard-path-or-size: 100M
        emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
        avd-name: test
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        working-directory: ./
        ndk: 23.0.7421159
        cmake: 3.10.2.4988404
        channel: beta
        script: echo "Generated AVD snapshot for caching."

    - uses: actions/checkout@v2
      with:
        repository: 'o01eg/python-cmake-buildsystem'
        ref: 'android-initial-support'
        path: 'build-python/python-cmake-buildsystem'

    - name: run action
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: ${{ matrix.arch }}
        profile: Galaxy Nexus
        cores: 2
        ram-size: 2048M
        sdcard-path-or-size: 100M
        emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
        avd-name: test
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        working-directory: build-python/python-cmake-buildsystem
        ndk: 23.0.7421159
        cmake: 3.10.2.4988404
        channel: beta
        script: |
          # ls -lR /Users/runner/Library/Android/sdk
          adb devices
          mkdir ../python-build
          mkdir ../python-install-prefix
          cd ../python-build
          /Users/runner/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=../python-install-prefix -DCMAKE_TOOLCHAIN_FILE=/Users/runner/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.ndk-arch }} -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/runner/work/freeorion-sdk/freeorion-sdk/.github/workflows/adb-emu.sh -DANDROID_ALLOW_UNDEFINED_SYMBOLS=On -DENABLE_DECIMAL=Off -DENABLE_CTYPES=Off -DENABLE_CODECS_JP=OFF -DENABLE_CODECS_KR=OFF -DENABLE_CODECS_TW=OFF -DENABLE_MULTIBYTECODEC=OFF -DENABLE_CODECS_CN=OFF -DENABLE_CODECS_HK=OFF -DENABLE_CODECS_ISO2022=OFF -DBUILD_EXTENSIONS_AS_BUILTIN=On -DANDROID_PLATFORM=android-21 ../python-cmake-buildsystem/
          /Users/runner/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake --build . -- VERBOSE=1
          /Users/runner/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake --build . --target install

    - name: Pack Python SDK
      shell: bash
      run: |
        cd build-python/python-install-prefix/lib/python3.6
        zip -r -9 -q --exclude=*.pyc --exclude=*.a --exclude=*.so ../../../python36.zip .
        cd ../..
        zip -r -9 -q ../python-3.6-sdk-${{ matrix.ndk-arch }}.zip include/ lib/libpython3.6m.a
        cd ..

    - uses: actions/upload-artifact@v2
      with:
        name: python SDK
        path: |
          build-python/python36.zip
          build-python/python-3.6-sdk-${{ matrix.ndk-arch }}.zip

