name: "Windows build"

on:
  push:
  pull_request:

jobs:
  build-windows:
    name: ${{ matrix.toolset }}-${{ matrix.arch }} on ${{ matrix.msvs }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [Win32, x64]
        toolset: [v143]
        msvs: ['Visual Studio 17 2022']
        vs-versions: ['[17.0,17.30)']
        os: [windows-2022]
        include:
          - arch: Win32
            toolset: v142
            msvs: 'Visual Studio 16 2019'
            vs-versions: '[16.0,16.30)'
            os: windows-2019
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: ${{ matrix.vs-versions }}
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -G "${{ matrix.msvs }}" -T ${{ matrix.toolset }} -A ${{ matrix.arch }} ..
      - name: Build
        run: |
          cd build
          cmake --build . --config RelWithDebInfo -- /verbosity:d
      - name: Artifact
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          name: Windows SDK
          path: |
            build/FreeOrionSDK_*_MSVC-${{ matrix.toolset }}-${{ matrix.arch }}.zip
      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: prepare-release-options
        run: |
          echo "release-name=$(git tag -ln --format '%(subject)' ${{ github.ref_name }})" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v1
        name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: ${{ steps.prepare-release-options.outputs.release-name }}
          draft: true
          files: |
            build/FreeOrionSDK_*_MSVC-${{ matrix.toolset }}-${{ matrix.arch }}.zip
          token: ${{ secrets.RELEASE_TOKEN }}
